export type NodeCategory = 'browser' | 'control' | 'variable' | 'assertion' | 'interaction';

export interface NodeParameter {
  name: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'select' | 'textarea' | 'variable';
  required?: boolean;
  defaultValue?: string | number | boolean;
  options?: { label: string; value: string }[];
  description?: string;
  variableSupport?: boolean;
}

export interface NodeTypeDefinition {
  type: string;
  label: string;
  category: NodeCategory;
  description: string;
  icon: string;
  color: string;
  parameters: NodeParameter[];
  inputs: number;
  outputs: number;
}

export interface FlowNodeData {
  label: string;
  type: string;
  parameters: Record<string, string | number | boolean>;
  description?: string;
  icon?: string;
  color?: string;
  isExecuting?: boolean;
}

export interface FlowEdgeData {
  label?: string;
}

export const NODE_DEFINITIONS: NodeTypeDefinition[] = [
  {
    type: 'open',
    label: '打开浏览器',
    category: 'browser',
    description: '启动浏览器并导航到指定URL',
    icon: 'Globe',
    color: '#3b82f6',
    inputs: 0,
    outputs: 1,
    parameters: [
      {
        name: 'browserType',
        label: '浏览器类型',
        type: 'select',
        defaultValue: 'chromium',
        options: [
          { label: 'Chromium', value: 'chromium' },
          { label: 'Firefox', value: 'firefox' },
          { label: 'WebKit', value: 'webkit' },
        ],
        description: '选择浏览器引擎',
      },
      {
        name: 'url',
        label: 'URL',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '导航到的URL地址',
        variableSupport: true,
      },
      {
        name: 'headless',
        label: '无头模式',
        type: 'select',
        defaultValue: 'true',
        options: [
          { label: '无头模式（后台运行）', value: 'true' },
          { label: '有头模式（显示浏览器）', value: 'false' },
        ],
        description: '是否显示浏览器窗口',
      },
      {
        name: 'viewport',
        label: '视口大小',
        type: 'select',
        defaultValue: '1280x720',
        options: [
          { label: '1280×720 (HD)', value: '1280x720' },
          { label: '1920×1080 (Full HD)', value: '1920x1080' },
          { label: '1366×768 (常见笔记本)', value: '1366x768' },
          { label: '375×667 (iPhone SE)', value: '375x667' },
          { label: '390×844 (iPhone 14)', value: '390x844' },
          { label: '自定义', value: 'custom' },
        ],
        description: '浏览器视口尺寸',
      },
      {
        name: 'locale',
        label: '语言区域',
        type: 'select',
        defaultValue: 'zh-CN',
        options: [
          { label: '简体中文', value: 'zh-CN' },
          { label: '繁体中文', value: 'zh-TW' },
          { label: '英语', value: 'en-US' },
          { label: '日语', value: 'ja-JP' },
          { label: '韩语', value: 'ko-KR' },
        ],
        description: '浏览器语言设置',
      },
    ],
  },
  {
    type: 'goto',
    label: '跳转页面',
    category: 'browser',
    description: '导航到指定URL',
    icon: 'Navigation',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'url',
        label: 'URL',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '目标URL地址',
        variableSupport: true,
      },
      {
        name: 'waitUntil',
        label: '等待条件',
        type: 'select',
        defaultValue: 'load',
        options: [
          { label: 'load - 页面load事件', value: 'load' },
          { label: 'domcontentloaded - DOM解析完成', value: 'domcontentloaded' },
          { label: 'networkidle - 网络空闲', value: 'networkidle' },
          { label: 'commit - 收到网络响应', value: 'commit' },
        ],
        description: '何时认为导航完成',
      },
    ],
  },
  {
    type: 'click',
    label: '点击元素',
    category: 'interaction',
    description: '点击页面上的元素',
    icon: 'MousePointer',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: 'CSS/XPath选择器',
        variableSupport: true,
      },
      {
        name: 'button',
        label: '鼠标按键',
        type: 'select',
        defaultValue: 'left',
        options: [
          { label: '左键', value: 'left' },
          { label: '右键', value: 'right' },
          { label: '中键', value: 'middle' },
        ],
        description: '点击使用的鼠标按键',
      },
      {
        name: 'clickCount',
        label: '点击次数',
        type: 'select',
        defaultValue: '1',
        options: [
          { label: '单击', value: '1' },
          { label: '双击', value: '2' },
          { label: '三击', value: '3' },
        ],
        description: '点击次数',
      },
      {
        name: 'modifiers',
        label: '修饰键',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '无', value: 'none' },
          { label: 'Shift', value: 'Shift' },
          { label: 'Control', value: 'Control' },
          { label: 'Alt', value: 'Alt' },
          { label: 'Meta (Cmd)', value: 'Meta' },
        ],
        description: '按住修饰键点击',
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 30000,
        description: '等待元素出现的超时时间',
      },
      {
        name: 'force',
        label: '强制点击',
        type: 'select',
        defaultValue: 'false',
        options: [
          { label: '否', value: 'false' },
          { label: '是（跳过可操作性检查）', value: 'true' },
        ],
        description: '跳过可操作性检查直接点击',
      },
    ],
  },
  {
    type: 'fill',
    label: '填充输入',
    category: 'interaction',
    description: '填充输入框内容',
    icon: 'Type',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '输入框的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'value',
        label: '填充值',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要填充的文本内容',
        variableSupport: true,
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 30000,
        description: '等待元素出现的超时时间',
      },
      {
        name: 'submit',
        label: '填充后提交',
        type: 'select',
        defaultValue: 'false',
        options: [
          { label: '否', value: 'false' },
          { label: '是（按Enter提交）', value: 'true' },
        ],
        description: '填充后是否按Enter提交',
      },
    ],
  },
  {
    type: 'type',
    label: '输入文本',
    category: 'interaction',
    description: '模拟键盘逐字输入',
    icon: 'Keyboard',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '目标元素的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'text',
        label: '输入文本',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要输入的文本',
        variableSupport: true,
      },
      {
        name: 'delay',
        label: '输入间隔(ms)',
        type: 'number',
        defaultValue: 0,
        description: '每个字符之间的延迟时间',
      },
    ],
  },
  {
    type: 'press',
    label: '按键操作',
    category: 'interaction',
    description: '按下键盘按键或组合键',
    icon: 'Keyboard',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        defaultValue: '',
        description: '目标元素（留空则对页面按键）',
        variableSupport: true,
      },
      {
        name: 'key',
        label: '按键',
        type: 'select',
        required: true,
        defaultValue: 'Enter',
        options: [
          { label: 'Enter', value: 'Enter' },
          { label: 'Tab', value: 'Tab' },
          { label: 'Escape', value: 'Escape' },
          { label: 'Backspace', value: 'Backspace' },
          { label: 'Delete', value: 'Delete' },
          { label: 'ArrowDown', value: 'ArrowDown' },
          { label: 'ArrowUp', value: 'ArrowUp' },
          { label: 'ArrowLeft', value: 'ArrowLeft' },
          { label: 'ArrowRight', value: 'ArrowRight' },
          { label: 'Home', value: 'Home' },
          { label: 'End', value: 'End' },
          { label: 'PageDown', value: 'PageDown' },
          { label: 'PageUp', value: 'PageUp' },
          { label: 'Space', value: ' ' },
          { label: 'Control+A (全选)', value: 'Control+a' },
          { label: 'Control+C (复制)', value: 'Control+c' },
          { label: 'Control+V (粘贴)', value: 'Control+v' },
          { label: 'Control+Z (撤销)', value: 'Control+z' },
          { label: 'Meta+A (全选 Mac)', value: 'Meta+a' },
        ],
        description: '要按下的键或组合键',
      },
    ],
  },
  {
    type: 'checkbox',
    label: '勾选/取消勾选',
    category: 'interaction',
    description: '勾选或取消勾选复选框/单选按钮',
    icon: 'CheckSquare',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '复选框/单选按钮的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'action',
        label: '操作',
        type: 'select',
        defaultValue: 'check',
        options: [
          { label: '勾选', value: 'check' },
          { label: '取消勾选', value: 'uncheck' },
        ],
        description: '勾选或取消勾选',
      },
    ],
  },
  {
    type: 'selectOption',
    label: '选择下拉选项',
    category: 'interaction',
    description: '选择下拉框中的选项',
    icon: 'List',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: 'select元素的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'value',
        label: '选项值',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要选择的选项值或标签',
        variableSupport: true,
      },
      {
        name: 'selectBy',
        label: '选择方式',
        type: 'select',
        defaultValue: 'value',
        options: [
          { label: '按值选择', value: 'value' },
          { label: '按标签选择', value: 'label' },
          { label: '按索引选择', value: 'index' },
        ],
        description: '选择选项的方式',
      },
    ],
  },
  {
    type: 'upload',
    label: '上传文件',
    category: 'interaction',
    description: '上传文件到文件输入框',
    icon: 'Upload',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: 'input[type=file]的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'filePath',
        label: '文件路径',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要上传的文件路径',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'hover',
    label: '悬停元素',
    category: 'interaction',
    description: '将鼠标悬停在元素上',
    icon: 'MousePointer',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '目标元素的CSS选择器',
        variableSupport: true,
      },
      {
        name: 'modifiers',
        label: '修饰键',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '无', value: 'none' },
          { label: 'Shift', value: 'Shift' },
          { label: 'Control', value: 'Control' },
          { label: 'Alt', value: 'Alt' },
          { label: 'Meta (Cmd)', value: 'Meta' },
        ],
        description: '悬停时按住的修饰键',
      },
    ],
  },
  {
    type: 'screenshot',
    label: '截图',
    category: 'browser',
    description: '保存页面截图',
    icon: 'Camera',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'path',
        label: '保存路径',
        type: 'variable',
        defaultValue: 'screenshot.png',
        description: '截图保存路径',
        variableSupport: true,
      },
      {
        name: 'fullPage',
        label: '完整页面',
        type: 'select',
        defaultValue: 'false',
        options: [
          { label: '仅视口', value: 'false' },
          { label: '完整页面', value: 'true' },
        ],
        description: '是否截取完整页面',
      },
      {
        name: 'target',
        label: '截图目标',
        type: 'select',
        defaultValue: 'page',
        options: [
          { label: '整个页面', value: 'page' },
          { label: '指定元素', value: 'element' },
        ],
        description: '截图的目标',
      },
      {
        name: 'selector',
        label: '元素选择器',
        type: 'variable',
        defaultValue: '',
        description: '当目标为元素时的CSS选择器',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'waitForSelector',
    label: '等待元素',
    category: 'browser',
    description: '等待元素出现在页面中',
    icon: 'Clock',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要等待的元素CSS选择器',
        variableSupport: true,
      },
      {
        name: 'state',
        label: '等待状态',
        type: 'select',
        defaultValue: 'visible',
        options: [
          { label: 'visible - 可见', value: 'visible' },
          { label: 'hidden - 隐藏', value: 'hidden' },
          { label: 'attached - 存在于DOM', value: 'attached' },
          { label: 'detached - 从DOM移除', value: 'detached' },
        ],
        description: '等待元素达到的状态',
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 30000,
        description: '最大等待时间',
      },
    ],
  },
  {
    type: 'waitForTimeout',
    label: '等待时间',
    category: 'browser',
    description: '固定等待一段时间',
    icon: 'Timer',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'timeout',
        label: '等待时间(ms)',
        type: 'number',
        required: true,
        defaultValue: 1000,
        description: '等待的毫秒数',
      },
    ],
  },
  {
    type: 'waitForUrl',
    label: '等待URL',
    category: 'browser',
    description: '等待页面URL匹配指定模式',
    icon: 'Navigation',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'urlPattern',
        label: 'URL匹配模式',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: 'URL字符串或正则表达式',
        variableSupport: true,
      },
      {
        name: 'matchType',
        label: '匹配方式',
        type: 'select',
        defaultValue: 'contains',
        options: [
          { label: '包含', value: 'contains' },
          { label: '精确匹配', value: 'exact' },
          { label: '正则匹配', value: 'regex' },
        ],
        description: 'URL匹配方式',
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 30000,
        description: '最大等待时间',
      },
    ],
  },
  {
    type: 'close',
    label: '关闭浏览器',
    category: 'browser',
    description: '关闭浏览器实例',
    icon: 'X',
    color: '#3b82f6',
    inputs: 1,
    outputs: 0,
    parameters: [],
  },
  {
    type: 'if',
    label: '条件判断',
    category: 'control',
    description: 'if/else条件分支',
    icon: 'GitBranch',
    color: '#f59e0b',
    inputs: 1,
    outputs: 2,
    parameters: [
      {
        name: 'condition',
        label: '条件类型',
        type: 'select',
        required: true,
        defaultValue: 'selectorExists',
        options: [
          { label: '元素存在', value: 'selectorExists' },
          { label: '元素可见', value: 'selectorVisible' },
          { label: '文本包含', value: 'textContains' },
          { label: 'URL匹配', value: 'urlMatches' },
          { label: '元素可编辑', value: 'selectorEditable' },
          { label: '元素已勾选', value: 'selectorChecked' },
          { label: '元素已启用', value: 'selectorEnabled' },
          { label: '变量有值', value: 'variableTruthy' },
        ],
        description: '判断条件的类型',
      },
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        defaultValue: '',
        description: '条件判断的元素选择器',
        variableSupport: true,
      },
      {
        name: 'text',
        label: '文本内容',
        type: 'variable',
        defaultValue: '',
        description: '文本包含条件时的文本',
        variableSupport: true,
      },
      {
        name: 'url',
        label: 'URL',
        type: 'variable',
        defaultValue: '',
        description: 'URL匹配条件时的URL',
        variableSupport: true,
      },
      {
        name: 'variableName',
        label: '变量名',
        type: 'variable',
        defaultValue: '',
        description: '变量条件时的变量名',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'while',
    label: '循环执行',
    category: 'control',
    description: 'while循环执行',
    icon: 'Repeat',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'condition',
        label: '条件类型',
        type: 'select',
        required: true,
        defaultValue: 'selectorExists',
        options: [
          { label: '元素存在', value: 'selectorExists' },
          { label: '元素可见', value: 'selectorVisible' },
          { label: '文本包含', value: 'textContains' },
          { label: 'URL匹配', value: 'urlMatches' },
          { label: '元素可编辑', value: 'selectorEditable' },
          { label: '元素已勾选', value: 'selectorChecked' },
          { label: '变量有值', value: 'variableTruthy' },
        ],
        description: '循环条件的类型',
      },
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        defaultValue: '',
        description: '条件判断的元素选择器',
        variableSupport: true,
      },
      {
        name: 'text',
        label: '文本内容',
        type: 'variable',
        defaultValue: '',
        description: '文本包含条件时的文本',
        variableSupport: true,
      },
      {
        name: 'url',
        label: 'URL',
        type: 'variable',
        defaultValue: '',
        description: 'URL匹配条件时的URL',
        variableSupport: true,
      },
      {
        name: 'variableName',
        label: '变量名',
        type: 'variable',
        defaultValue: '',
        description: '变量条件时的变量名',
        variableSupport: true,
      },
      {
        name: 'maxIterations',
        label: '最大循环次数',
        type: 'number',
        defaultValue: 10,
        description: '防止无限循环的最大迭代次数',
      },
    ],
  },
  {
    type: 'foreach',
    label: '遍历元素',
    category: 'control',
    description: '遍历匹配选择器的所有元素',
    icon: 'List',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要遍历的元素选择器',
        variableSupport: true,
      },
      {
        name: 'variableName',
        label: '循环变量名',
        type: 'string',
        required: true,
        defaultValue: 'item',
        description: '当前遍历元素的变量名',
      },
    ],
  },
  {
    type: 'setVariable',
    label: '设置变量',
    category: 'variable',
    description: '定义或设置一个变量',
    icon: 'Variable',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'name',
        label: '变量名',
        type: 'string',
        required: true,
        defaultValue: '',
        description: '变量的名称（英文）',
      },
      {
        name: 'value',
        label: '变量值',
        type: 'variable',
        defaultValue: '',
        description: '变量的值，支持引用其他变量 ${varName}',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'extract',
    label: '提取内容',
    category: 'variable',
    description: '从页面提取内容到变量',
    icon: 'Eye',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要提取内容的元素选择器',
        variableSupport: true,
      },
      {
        name: 'attribute',
        label: '提取属性',
        type: 'select',
        required: true,
        defaultValue: 'textContent',
        options: [
          { label: '文本内容 (textContent)', value: 'textContent' },
          { label: '内部HTML (innerHTML)', value: 'innerHTML' },
          { label: '输入值 (value)', value: 'value' },
          { label: '链接地址 (href)', value: 'href' },
          { label: '图片地址 (src)', value: 'src' },
          { label: 'CSS类名 (className)', value: 'className' },
          { label: '元素ID (id)', value: 'id' },
          { label: '自定义属性', value: 'custom' },
        ],
        description: '要提取的元素属性',
      },
      {
        name: 'customAttribute',
        label: '自定义属性名',
        type: 'string',
        defaultValue: '',
        description: '当提取属性为"自定义"时的属性名',
      },
      {
        name: 'variableName',
        label: '保存到变量',
        type: 'string',
        required: true,
        defaultValue: '',
        description: '提取结果保存到的变量名',
      },
    ],
  },
  {
    type: 'assertVisible',
    label: '断言-元素可见',
    category: 'assertion',
    description: '断言元素在页面上可见',
    icon: 'Eye',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要断言的元素选择器',
        variableSupport: true,
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 5000,
        description: '断言超时时间',
      },
    ],
  },
  {
    type: 'assertText',
    label: '断言-文本内容',
    category: 'assertion',
    description: '断言元素包含指定文本',
    icon: 'Type',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要断言的元素选择器',
        variableSupport: true,
      },
      {
        name: 'expectedText',
        label: '期望文本',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '期望包含的文本内容',
        variableSupport: true,
      },
      {
        name: 'matchType',
        label: '匹配方式',
        type: 'select',
        defaultValue: 'contains',
        options: [
          { label: '包含', value: 'contains' },
          { label: '精确匹配', value: 'exact' },
          { label: '正则匹配', value: 'regex' },
        ],
        description: '文本匹配方式',
      },
      {
        name: 'timeout',
        label: '超时(ms)',
        type: 'number',
        defaultValue: 5000,
        description: '断言超时时间',
      },
    ],
  },
  {
    type: 'assertUrl',
    label: '断言-页面URL',
    category: 'assertion',
    description: '断言当前页面URL匹配',
    icon: 'Navigation',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'expectedUrl',
        label: '期望URL',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '期望的URL或匹配模式',
        variableSupport: true,
      },
      {
        name: 'matchType',
        label: '匹配方式',
        type: 'select',
        defaultValue: 'contains',
        options: [
          { label: '包含', value: 'contains' },
          { label: '精确匹配', value: 'exact' },
          { label: '正则匹配', value: 'regex' },
        ],
        description: 'URL匹配方式',
      },
    ],
  },
  {
    type: 'assertTitle',
    label: '断言-页面标题',
    category: 'assertion',
    description: '断言页面标题包含指定文本',
    icon: 'Type',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'expectedTitle',
        label: '期望标题',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '期望的页面标题',
        variableSupport: true,
      },
      {
        name: 'matchType',
        label: '匹配方式',
        type: 'select',
        defaultValue: 'contains',
        options: [
          { label: '包含', value: 'contains' },
          { label: '精确匹配', value: 'exact' },
          { label: '正则匹配', value: 'regex' },
        ],
        description: '标题匹配方式',
      },
    ],
  },
  {
    type: 'assertElementCount',
    label: '断言-元素数量',
    category: 'assertion',
    description: '断言匹配选择器的元素数量',
    icon: 'Hash',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要计数的元素选择器',
        variableSupport: true,
      },
      {
        name: 'comparison',
        label: '比较方式',
        type: 'select',
        defaultValue: 'equal',
        options: [
          { label: '等于', value: 'equal' },
          { label: '大于', value: 'greaterThan' },
          { label: '小于', value: 'lessThan' },
          { label: '大于等于', value: 'greaterThanOrEqual' },
          { label: '小于等于', value: 'lessThanOrEqual' },
        ],
        description: '数量比较方式',
      },
      {
        name: 'expectedCount',
        label: '期望数量',
        type: 'number',
        required: true,
        defaultValue: 1,
        description: '期望的元素数量',
      },
    ],
  },
  {
    type: 'assertAttribute',
    label: '断言-元素属性',
    category: 'assertion',
    description: '断言元素具有指定属性值',
    icon: 'Tag',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'selector',
        label: '选择器',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '要断言的元素选择器',
        variableSupport: true,
      },
      {
        name: 'attribute',
        label: '属性名',
        type: 'select',
        required: true,
        defaultValue: 'value',
        options: [
          { label: '值 (value)', value: 'value' },
          { label: '链接 (href)', value: 'href' },
          { label: '图片 (src)', value: 'src' },
          { label: '类名 (class)', value: 'class' },
          { label: '禁用状态 (disabled)', value: 'disabled' },
          { label: '自定义属性', value: 'custom' },
        ],
        description: '要断言的属性',
      },
      {
        name: 'customAttribute',
        label: '自定义属性名',
        type: 'string',
        defaultValue: '',
        description: '自定义属性名',
      },
      {
        name: 'expectedValue',
        label: '期望属性值',
        type: 'variable',
        required: true,
        defaultValue: '',
        description: '期望的属性值',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'saveAuth',
    label: '保存认证状态',
    category: 'browser',
    description: '保存当前浏览器的认证状态（cookies、localStorage等）',
    icon: 'Save',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'path',
        label: '保存路径',
        type: 'variable',
        defaultValue: 'auth.json',
        description: '认证状态保存文件路径',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'loadAuth',
    label: '加载认证状态',
    category: 'browser',
    description: '加载之前保存的认证状态',
    icon: 'Key',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'path',
        label: '文件路径',
        type: 'variable',
        defaultValue: 'auth.json',
        description: '认证状态文件路径',
        variableSupport: true,
      },
    ],
  },
  {
    type: 'evaluate',
    label: '执行JS表达式',
    category: 'variable',
    description: '在页面上下文中执行JavaScript表达式',
    icon: 'Code',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
    parameters: [
      {
        name: 'expression',
        label: 'JS表达式',
        type: 'textarea',
        required: true,
        defaultValue: '',
        description: '在页面上下文中执行的JavaScript代码',
      },
      {
        name: 'variableName',
        label: '结果保存到变量',
        type: 'string',
        defaultValue: '',
        description: '执行结果保存到的变量名（留空则不保存）',
      },
    ],
  },
];

export function getNodeDefinition(type: string): NodeTypeDefinition | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type);
}

export function getNodesByCategory(category: NodeCategory): NodeTypeDefinition[] {
  return NODE_DEFINITIONS.filter((n) => n.category === category);
}
